### ISSUE TITLE
No support for large images

### ISSUE THREAD

**Issue by mplumador** [Zryx51/Class-Project#12]
We are somewhat capped off it appears for sending data to the DB, we may need to find some type of encoding algorithm to encode/decode image data before sending it!
![image](https://user-images.githubusercontent.com/47329146/55908408-64c7ea00-5ba7-11e9-819e-b69d0d2bcc89.png)

The image in question I was trying to store was this (It took forever and it's gone!!!!):
![image](https://user-images.githubusercontent.com/47329146/55908449-7f9a5e80-5ba7-11e9-9ebc-0babc668911a.png)

**Comment by Danimal97** [comment]
Have you considered using the Huffman Encoding algorithm?

**Comment by mplumador** [comment]
https://stackoverflow.com/questions/19917401/error-request-entity-too-large

**Comment by mplumador** [comment]
Added support for images up to 15 mb in size.
